### ISSUE TITLE
No page numbers, only Loc in Kindle

### ISSUE THREAD

**Issue by wphqe** [standardebooks/fyodor-dostoevsky_crime-and-punishment_constance-garnett#6]
Hi, I'm not sure which repo is best to make this issue but hopefully this is ok. I have downloaded the .azw3 file to my Kindle Paperwhite but page numbers do not appear while reading the book, only the "loc" location numbers. I've noticed this with other Standard Ebook files. Is this a known bug or have I done something wrong?

**Comment by acabal** [comment]
This is not a bug in the ebook, it's a bug in the Kindle software. As far as I know Kindle has never calculated page numbers for side loaded ebooks. You should report it to Amazon.
